export const DASHBOARD_ACTIVE_REFRESH_INTERVAL_MS = 60_000;
export const DASHBOARD_BACKGROUND_REFRESH_INTERVAL_MS = 5 * 60_000;
export const DEMO_MRR_MINOR = 10_000_000;
export const FALLBACK_CURRENCY = "eur";
