/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PixelizerRouteImport } from './routes/pixelizer'
import { Route as ApiGoogleCalendarCallbackRouteImport } from './routes/api/google-calendar/callback'
import { Route as ApiGoogleCalendarLoginRouteImport } from './routes/api/google-calendar/login'
import { Route as ApiSpotifyCallbackRouteImport } from './routes/api/spotify/callback'
import { Route as ApiSpotifyLoginRouteImport } from './routes/api/spotify/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PixelizerRoute = PixelizerRouteImport.update({
  id: '/pixelizer',
  path: '/pixelizer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleCalendarCallbackRoute =
  ApiGoogleCalendarCallbackRouteImport.update({
    id: '/api/google-calendar/callback',
    path: '/api/google-calendar/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGoogleCalendarLoginRoute = ApiGoogleCalendarLoginRouteImport.update({
  id: '/api/google-calendar/login',
  path: '/api/google-calendar/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpotifyCallbackRoute = ApiSpotifyCallbackRouteImport.update({
  id: '/api/spotify/callback',
  path: '/api/spotify/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpotifyLoginRoute = ApiSpotifyLoginRouteImport.update({
  id: '/api/spotify/login',
  path: '/api/spotify/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pixelizer': typeof PixelizerRoute
  '/api/google-calendar/callback': typeof ApiGoogleCalendarCallbackRoute
  '/api/google-calendar/login': typeof ApiGoogleCalendarLoginRoute
  '/api/spotify/callback': typeof ApiSpotifyCallbackRoute
  '/api/spotify/login': typeof ApiSpotifyLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pixelizer': typeof PixelizerRoute
  '/api/google-calendar/callback': typeof ApiGoogleCalendarCallbackRoute
  '/api/google-calendar/login': typeof ApiGoogleCalendarLoginRoute
  '/api/spotify/callback': typeof ApiSpotifyCallbackRoute
  '/api/spotify/login': typeof ApiSpotifyLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pixelizer': typeof PixelizerRoute
  '/api/google-calendar/callback': typeof ApiGoogleCalendarCallbackRoute
  '/api/google-calendar/login': typeof ApiGoogleCalendarLoginRoute
  '/api/spotify/callback': typeof ApiSpotifyCallbackRoute
  '/api/spotify/login': typeof ApiSpotifyLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pixelizer'
    | '/api/google-calendar/callback'
    | '/api/google-calendar/login'
    | '/api/spotify/callback'
    | '/api/spotify/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pixelizer'
    | '/api/google-calendar/callback'
    | '/api/google-calendar/login'
    | '/api/spotify/callback'
    | '/api/spotify/login'
  id:
    | '__root__'
    | '/'
    | '/pixelizer'
    | '/api/google-calendar/callback'
    | '/api/google-calendar/login'
    | '/api/spotify/callback'
    | '/api/spotify/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PixelizerRoute: typeof PixelizerRoute
  ApiGoogleCalendarCallbackRoute: typeof ApiGoogleCalendarCallbackRoute
  ApiGoogleCalendarLoginRoute: typeof ApiGoogleCalendarLoginRoute
  ApiSpotifyCallbackRoute: typeof ApiSpotifyCallbackRoute
  ApiSpotifyLoginRoute: typeof ApiSpotifyLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pixelizer': {
      id: '/pixelizer'
      path: '/pixelizer'
      fullPath: '/pixelizer'
      preLoaderRoute: typeof PixelizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-calendar/callback': {
      id: '/api/google-calendar/callback'
      path: '/api/google-calendar/callback'
      fullPath: '/api/google-calendar/callback'
      preLoaderRoute: typeof ApiGoogleCalendarCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-calendar/login': {
      id: '/api/google-calendar/login'
      path: '/api/google-calendar/login'
      fullPath: '/api/google-calendar/login'
      preLoaderRoute: typeof ApiGoogleCalendarLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spotify/callback': {
      id: '/api/spotify/callback'
      path: '/api/spotify/callback'
      fullPath: '/api/spotify/callback'
      preLoaderRoute: typeof ApiSpotifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spotify/login': {
      id: '/api/spotify/login'
      path: '/api/spotify/login'
      fullPath: '/api/spotify/login'
      preLoaderRoute: typeof ApiSpotifyLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PixelizerRoute: PixelizerRoute,
  ApiGoogleCalendarCallbackRoute: ApiGoogleCalendarCallbackRoute,
  ApiGoogleCalendarLoginRoute: ApiGoogleCalendarLoginRoute,
  ApiSpotifyCallbackRoute: ApiSpotifyCallbackRoute,
  ApiSpotifyLoginRoute: ApiSpotifyLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
